project:
  type: website
  output-dir: docs

website:
  title: "Dmitry R."
  search: false
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Consulting"
        file: consulting.qmd
      - projects.qmd
      - text: "Research"
        file: research.qmd
      - text: "CV"
        file: about.qmd
      # - text: "Blog"
      #   file: blog.qmd
      - text: "Contact"
        file: contact.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/dmitryrastorguev/
      - icon: github
        href: https://github.com/drastorguev
      - icon: twitter
        href: https://mobile.twitter.com/dsrastorguev
      - icon: medium
        href: https://medium.com/@dmitryrastorguev
  page-footer:
    left: "Copyright 2022, Dmitry Rastorguev - Built using [Quarto](https://quarto.org/docs/websites/) - *Website is currently at work in progress stage* "
  google-analytics: "G-KGHL346XM6"
  cookie-consent:
    palette: dark
    type: express
  site-url: "https://rastorguev.co.uk/"
  twitter-card:
    card-style: summary_large_image
    creator: "@dsrastorguev"
    image: "/static/website_image.jpg"
  open-graph:
    locale: en_GB
    image: "/static/website_image.jpg"


format:
  html:
    theme: cosmo
    css: styles.css
